[[main]]
  name = "Chi siamo"
  url = "/about/"
  # "weight" defines the order of this menu item
  weight = 10
  # The "project" variable defines if this menu item is shown or hidden on the
  # main project pages. Please note that this is valid for projects listed in
  # the "projects" params at config.toml
  # Options:
  #   not set (default): shown on all pages
  #   "hide" hides it from the main project page but is shown elsewhere
  #   "only" hides it from the other pages and shows on project page only with
  #      a URL alteration to include the project path. For example:
  #      /about/ becomes /zeitshift/about/ in the zeitshift project page
  [main.params]
    project = "only"


[[main]]
  name = "Partecipare"
  url = "/participate/"
  weight = 20
  [main.params]
    project = "only"

[[main]]
  name = "Progetti"
  url = "/projects/"
  weight = 30
  [main.params]
    project = "hide"

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 40

[[main]]
  name = "Contatto"
  url = "/contact/"
  weight = 50

[[docs]]
name = "Progetti"
weight = 1
identifier = "projects"
url = "/projects/"

[[docs]]
name = "Zeit.shift"
weight = 10
identifier = "zeitshift"
url = "/zeitshift/"

[[languages]]
  name = "de"
  pre = "de"
  url = "/de"
  weight = 1

[[languages]]
  name = "en"
  pre = "en"
  url = "/en"
  weight = 2

# [[languages]]
#   name = "it"
#   pre = "it"
#   url = "/it"
#   weight = 3

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/zeit.shift"
  weight = 10

[[social]]
    name = "Instagram"
    pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-instagram\"><rect x=\"2\" y=\"2\" width=\"20\" height=\"20\" rx=\"5\" ry=\"5\"></rect><path d=\"M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z\"></path><line x1=\"17.5\" y1=\"6.5\" x2=\"17.51\" y2=\"6.5\"></line></svg>"
    url = "https://www.instagram.com/all4ling/"
    weight = 10

[[footer]]
    name = "Privacy"
    url = "https://www.eurac.edu/it/static/privacy-policy"
    weight = 10
