[[main]]
  name = "About"
  url = "/about/introduction/zeitshift"
  weight = 10

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 20

[[social]]
  name = "de"
  pre = "de"
  url = "/"
  weight = 1

[[social]]
  name = "en"
  pre = "en"
  url = "/en"
  weight = 2

[[social]]
  name = "it"
  pre = "it"
  url = "/it"
  weight = 3

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/zeit.shift"
  weight = 10

# [[social]]
#   name = "GitLab"
#   pre = '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="1em" height="1em" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><g fill="none" stroke="#626262" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22.65 14.39L12 22.13L1.35 14.39a.84.84 0 0 1-.3-.94l1.22-3.78l2.44-7.51A.42.42 0 0 1 4.82 2a.43.43 0 0 1 .58 0a.42.42 0 0 1 .11.18l2.44 7.49h8.1l2.44-7.51A.42.42 0 0 1 18.6 2a.43.43 0 0 1 .58 0a.42.42 0 0 1 .11.18l2.44 7.51L23 13.45a.84.84 0 0 1-.35.94z"/></g></svg>'
#   url = "https://gitlab.inf.unibz.it/commul/zeit.shift"
#   post = "v0.1.0"
#   weight = 50

# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10

# [[footer]]
#   name = "Community"
#   url = "/community/"
#   weight = 10
