# Meta Data for SEO

## Homepage
#
# Define these in _config.toml for each (supported) individual language
#
#title = "All4Ling"
#titleSeparator = "-"
#description = "All for Linguistics is an initiative of the Institute of Applied Linguistics of Eurac Research devoted to the development of Citizen Science projects and expertise at the intersection of Computational Linguistics and Digital Humanities."

## Documentation
# docsVersion = "1.0"

## Open Graph
# images = ["doks.png"]
# ogLocale = "en_US"
# domainTLD = "doks.netlify.app"
# titleHome = "Doks Theme"

## Twitter Cards
# twitterSite = "@getdoks"
# twitterCreator = "@henkverlinde"

## JSON-LD
# schemaType = "Person"
# schemaType = "Organization"
# schemaName = "Doks"
# schemaAuthor = "Henk Verlinde"
# schemaAuthorTwitter = "https://twitter.com/henkverlinde"
# schemaAuthorLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
# schemaAuthorGitHub = "https://github.com/h-enk"
# schemaLocale = "en-US"
# schemaLogo = "logo-doks.png"
# schemaLogoWidth = 512
# schemaLogoHeight = 512
# schemaImage = "doks.png"
# schemaImageWidth = 1280
# schemaImageHeight = 640
# schemaTwitter = "https://twitter.com/getdoks"
# schemaLinkedIn = ""
# schemaGitHub = "https://github.com/h-enk/doks"
# schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = true

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Footer
footer = "Powered by <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a> and <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>"

# Feed
# copyRight = "Copyright (c) 2021-2022 Eurac Research, Institute for Applied Linguistics"

# Alert
alert = false
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitLab"
#repoHost = "Gitea"
docsRepo = "https://gitlab.inf.unibz.it/commul/zeit.shift"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = false
lastMod = false

[options]
  lazySizes = true
  clipBoard = false
  highlight = false
  instantPage = false
  flexSearch = false
  darkMode = false
  bootStrapJs = false
  breadCrumb = true
  languageSwitch = true
  highLight = false
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
