---
image:
  name: klakegg/hugo:ext-ubuntu
  entrypoint: ['']

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  before_script:
    - apt-get update && apt-get install -y nodejs
  script:
  - npm install
  - hugo
  # except:
  # - master

pages:
  before_script:
    - apt-get update && apt-get install -y nodejs
  script:
  - npm install
  - hugo --baseURL "https://commul.pages.scientificnet.org/all4ling/www/"
  artifacts:
    paths:
    - public
  only:
  - master
