---
image:
  name: node:16
  entrypoint: ['']

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - npm install
  - $(npm bin)/hugo/hugo version
  # except:
  # - master

pages:
  script:
  - npm install
  - ./page_replication.sh
  - npm run build -- --baseURL ${CI_PAGES_URL}

  artifacts:
    paths:
    - public
  only:
  - master
