---
image:
  name: klakegg/hugo:ext-ubuntu
  entrypoint: ['']

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  before_script:
    - apt update && apt install -y npm
  script:
  - npm install
  - hugo
  # except:
  # - master

pages:
  before_script:
    - apt update && apt install -y npm
  script:
  - npm install
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
