---
image:
  name: klakegg/hugo:ext-ubuntu
  entrypoint: ['']

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - hugo
  # except:
  # - master

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
