---
image:
  name: klakegg/hugo:0.81.0-ext-ubuntu
  entrypoint: ['']

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  before_script:
    - apt-get update && apt-get install -y nodejs
  script:
  - npm install
  - hugo version
  # except:
  # - master

pages:
  before_script:
    - apt-get update && apt-get install -y nodejs
  script:
  - npm install
  - hugo version
  - hugo --baseURL https://all4ling.eurac.edu
  artifacts:
    paths:
    - public
  only:
  - master
